kind: pipeline

steps:
- name: test
  image: alpine
  environment:
    GH_USERNAME:
      from_secret: gh_username
    GH_TOKEN:
      from_secret: gh_token
  commands:
    - env


---
kind: pipeline
name: build-windows

platform:
  os: windows
  version: 1909

steps:
- name: build
  image: docker.enlyze.com/enlyze/windows-gateways-build-environment
  commands:
  - .\drone_build.ps1

- name: deploy
  image: docker.enlyze.com/enlyze/windows-gateways-build-environment
  environment:
    GH_USERNAME:
      from_secret: gh_username
    GH_TOKEN:
      from_secret: gh_token
  commands:
  - .\drone_deploy.ps1
  when:
    branch:
    - master
    event:
    - push
